name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  access_key: ${{secrets.AWS_ACCESS_KEY}}
  secret_key: ${{secrets.AWS_SECRET_KEY}}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      
    # Set Up The Java 
    - name: Setup JDK 1.8
      uses: actions/checkout@v3
      with:
        java-version: 1.8  
    - name: Build Code
      run: mvn -B package --file pom.xml
    #- name: Cache SonarCloud packages
    #  uses: actions/cache@v1
     # with:
      #   path: ~/.sonar/cache
       #  key: ${{ runner.os }}-sonar
        # restore-keys: ${{ runner.os }}-sonar
    #- name: Cache Maven packages
     # uses: actions/cache@v1
      #with:
       # path: ~/.m2
        #key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        #restore-keys: ${{ runner.os }}-m2
    - name: Sonar Scanner
     # uses: SonarSource/sonarcloud-github-action@master
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      run: mvn -B package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=rishikant4_github-actions
