name: 'MyWorkflow1'

on:
  push:
    branches: [ "master" ]
  pull_request:


    
jobs:
  build:
    name: 'github-actions-CI'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      
    # Set Up The Java 
    - name: Setup JDK 1.8
      uses: actions/checkout@v3
      with:
        java-version: 1.8  

    - name: Build with Maven
      id: build
      run: |
        mvn_output=$(mvn -B -X package --file pom.xml)
        echo "::set-output name=build-log::$mvn_output"

    - name: Print build log
      run: |
        echo "${{steps.build.outputs.build-log}}"

    - name: Print pom.xml
      run: |
        cat pom.xml
